import fs from 'node:fs/promises';
import path from 'node:path';
import { Presentation, PresentationFile } from '@oai/artifact-tool';
const SKILL=process.env.PRESENTATIONS_SKILL;
if(!SKILL)throw new Error('Set PRESENTATIONS_SKILL');
const {resolvePresentationFont,applyPresentationChartFont,finalizePresentation}=await import(path.join(SKILL,'container_tools/artifact_tool_utils.mjs'));
const ROOT=process.env.PROJECT_ROOT;
if(!ROOT)throw new Error('Set PROJECT_ROOT to the repository root');
const TMP=path.join(ROOT,'tmp/presentations/experimento');
const PY=process.env.PYTHON_EXECUTABLE || 'python3';
const FONT=resolvePresentationFont({fontFamily:'Arial'});
const C={navy:'#17324D',teal:'#087F8C',ink:'#253643',muted:'#586B79',ivory:'#F7F5F0',orange:'#BC5A3D',white:'#FFFFFF'};
const p=Presentation.create({slideSize:{width:1280,height:720}});
const notes=[]; const chartOwners=[]; const tableOwners=[];
function txt(s,str,x,y,w,h,size=30,color=C.ink,bold=false){const t=s.shapes.add({geometry:'textbox',name:str.slice(0,55),position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});t.text=str;t.text.style={typeface:FONT,fontSize:size,color,bold,autoFit:'none',verticalAlignment:'top',insets:{top:0,left:0,right:0,bottom:0}};return t;}
function slide(title,seconds,note,source,{dark=false,backup=false}={}){const s=p.slides.add();s.background.fill=dark?C.navy:C.ivory;const n=p.slides.items.length;txt(s,title,72,48,1136,110,44,dark?C.white:C.navy,true);txt(s,backup?'Apoio':`${n} / 15`,1110,677,98,24,17,dark?'#B6CCD8':C.muted);s.speakerNotes.textFrame.setText(`${backup?'Apoio opcional':`Tempo sugerido: ${seconds} s`}\n\n${note}\n\nFontes: ${source}`);notes.push({slide:n,title,seconds,backup,note,source});return s;}
function lead(s,str,y=175,dark=false){txt(s,str,72,y,1130,150,40,dark?C.white:C.navy,true);}
function pair(s,leftTitle,left,rightTitle,right,y=230){txt(s,leftTitle,72,y,520,54,30,C.teal,true);txt(s,left,72,y+74,520,275,29);txt(s,rightTitle,690,y,520,54,30,C.teal,true);txt(s,right,690,y+74,520,275,29);}
function rows(s,arr,y=200){arr.forEach((r,i)=>{txt(s,r[0],72,y+i*115,265,80,30,C.teal,true);txt(s,r[1],380,y+i*115,800,90,29);});}
async function img(s,file,x,y,w,h){s.images.add({blob:new Uint8Array(await fs.readFile(path.join(ROOT,'presentations/experimento/assets',file))),contentType:'image/png',alt:`Página do documento ${file}`,fit:'contain',position:{left:x,top:y,width:w,height:h}});}
function table(s,values,widths,y=190,h=360,size=27){const tb=s.tables.add({rows:values.length,columns:values[0].length,left:72,top:y,width:1136,height:h,columnWidths:widths,values});tb.borders.assign({fill:'#D7DFE2',width:.5,style:'solid'});for(let r=0;r<values.length;r++){tb.rows[r].height=h/values.length;for(let c=0;c<values[0].length;c++){const cell=tb.getCell(r,c);cell.fill=r===0?C.navy:C.ivory;cell.text.style={typeface:FONT,fontSize:size,color:r===0?C.white:C.ink,bold:r===0,insets:{top:12,bottom:8,left:14,right:14}};}}tableOwners.push(p.slides.items.length);return tb;}

let s=slide('Uma dissertação em poucos dias',60,'Abrir mostrando os artefatos reais. O agente produziu uma dissertação de 167 páginas e um artigo inicialmente de sete páginas. O manuscrito mostrado tem nove páginas após revisão posterior. Da criação ao encerramento do goal transcorreram 54h56min, arredondadas para 55 horas; desde o primeiro pedido foram cerca de 57 horas. O contador do goal marcou 30h51min, sem representar tempo de CPU. A provocação é o que uma entrega assim diz sobre a formação humana.','Relatório, abertura e apêndice D; PDFs originais.',{dark:true});await img(s,'dissertacao-001.png',72,195,268,360);await img(s,'artigo-1.png',376,195,268,360);txt(s,'167 páginas',85,568,260,45,29,C.white,true);txt(s,'Artigo: 9 páginas',378,568,300,45,29,C.white,true);txt(s,'55 horas',740,208,470,110,72,'#B8DCE1',true);txt(s,'no calendário do goal',746,322,470,65,29,C.white);txt(s,'31 horas',742,432,455,88,56,C.white,true);txt(s,'no contador do goal',746,521,460,48,29,C.white);txt(s,'O artigo foi revisado após o goal. Nenhum título foi concedido.',72,643,1125,32,21,'#C4D6DF');
s=slide('O que o diploma deve atestar?',120,'Apresentar a pergunta antes dos detalhes de execução. Um documento pode ser útil para avaliar o resultado científico e insuficiente para demonstrar o domínio individual. Separar aprendizagem, qualidade e responsabilidade. Evitar dizer que o PDF não prova nada ou que a formação perdeu valor. O experimento não mediu aprendizagem.','Relatório, abertura e seção 3.');txt(s,'Se um agente produz\na dissertação,',72,200,1120,150,62,C.navy,true);txt(s,'como demonstramos\na formação do pesquisador?',72,388,1120,155,58,C.teal,true);
s=slide('Uma intenção ampla, um TG de partida',80,'O proponente declara não dominar o tema e não ter fornecido hipóteses, equações ou código. Forneceu o TG de 2003 e solicitou continuidade implementável, validável e com potencial de publicação. O texto do slide é uma síntese dos pedidos, não uma citação literal. Não afirmar ausência completa de intervenção: houve acompanhamento e pareceres encaminhados.','TG_Wayne.pdf; relatório, apêndices A a A.2.');await img(s,'tg-01.png',72,177,310,433);txt(s,'Propor uma continuação.\nImplementar e validar.\nEscrever a dissertação.',450,211,740,200,40,C.navy,true);txt(s,'O proponente não dominava o tema\ne não forneceu uma hipótese nova.',450,481,740,110,30,C.teal);
s=slide('A delegação e a revisão',80,'Ler o diagrama da esquerda para a direita. O usuário definiu a intenção e acompanhou o processo. O Codex Astra coordenou três subagentes e formulou, implementou e redigiu. Os pareceres do Gemini chegaram por intermédio do usuário. A seta dupla indica crítica e resposta, não uma integração automática entre sistemas. Não houve revisão cega nem avaliação formal por pares humanos.','Relatório, abertura, seção 2 e apêndices A e B.');
function node(label,x){const a=s.shapes.add({geometry:'rect',name:label,position:{left:x,top:248,width:285,height:100},fill:C.navy,line:{fill:C.navy,width:0}});a.text=label;a.text.style={typeface:FONT,fontSize:36,bold:true,color:C.white,alignment:'center',verticalAlignment:'middle'};return a;}
const u=node('Usuário',72),a=node('Codex Astra',490),g=node('Gemini',908);s.shapes.connect(u,a,{kind:'straight',fromSide:'right',toSide:'left',line:{fill:C.teal,width:3},tail:{type:'arrow',width:'med',length:'med'}});s.shapes.connect(a,g,{kind:'straight',fromSide:'right',toSide:'left',line:{fill:C.teal,width:3},head:{type:'arrow',width:'med',length:'med'},tail:{type:'arrow',width:'med',length:'med'}});txt(s,'Direção e\nacompanhamento',72,385,310,105,29);txt(s,'Formulação, código\ne escrita',490,385,330,105,29);txt(s,'Dois pareceres\nencaminhados pelo usuário',908,385,300,150,28);txt(s,'Três subagentes apoiaram a execução do Codex.',72,586,1100,45,29,C.teal,true);
s=slide('A primeira decisão foi descartar caminhos',90,'Em vez de alegar que repetiu o TG como descoberta, o agente reconheceu resultados já publicados em 2004 e antecedentes posteriores. Um trabalho de 2026 motivou uma comparação entre simplificações. Não dizer que esse artigo continha uma falha já provada. O recorte foi uma pergunta de confiabilidade com originalidade candidata.','Relatório, seção 1; protocolo e decisão de recorte na literatura.');txt(s,'2003 / 2004',72,205,310,70,44,C.teal,true);txt(s,'O TG já tinha resultados publicados.',430,210,770,95,36,C.navy,true);txt(s,'2026',72,360,310,70,44,C.teal,true);txt(s,'A literatura sugeriu uma comparação\nainda a testar.',430,359,770,110,36,C.navy,true);txt(s,'Pergunta escolhida: quando simplificar os dados muda a resposta?',72,555,1120,88,32,C.orange,true);
s=slide('Um teste encontrou confiança excessiva',100,'Explicar sem física: em dados simulados sabemos a resposta. Uma faixa de incerteza que promete conter essa resposta em 90% dos casos precisa passar por um teste. Em um parâmetro de ruído ela continha a resposta em 313 de 500 casos, 62,6%. Isso demonstra uma limitação daquela aproximação naquele teste, não erro de todos os métodos. O problema tornou-se parte do resultado científico.','Relatório, seção 2 e apêndice B.1; review_efac_coverage.json.');txt(s,'90%',72,200,510,115,90,C.teal,true);txt(s,'era a cobertura anunciada',76,345,520,100,31);txt(s,'62,6%',695,200,510,115,90,C.orange,true);txt(s,'foi a cobertura no teste',699,345,510,100,31);txt(s,'Em 313 de 500 casos, a faixa continha a resposta conhecida.',72,523,1120,105,34,C.navy,true);
s=slide('Uma IA criticou. A outra conferiu.',120,'Distinguir os ciclos. No primeiro, o Codex conferiu o parecer e acrescentou 300 análises em 50 casos sob condições fixadas, além de um estudo temporal. O complemento resolveu um problema menor. No segundo, o agente revisou o artigo sem simulações novas e recusou extrapolações: falha em simulação não prova falha inevitável em dados reais. As frases do slide são sínteses, não transcrições. A revisão foi mediada pelo usuário e não certifica o resultado.','Relatório, seção 2 e apêndice A.2; article/REVISION_NOTES.md.',{dark:true});txt(s,'Crítica à dissertação',72,203,535,70,36,'#B8DCE1',true);txt(s,'50 casos adicionais\n300 análises',72,315,535,145,44,C.white,true);txt(s,'Crítica ao manuscrito',704,203,500,70,36,'#B8DCE1',true);txt(s,'Revisão do texto\nRecusa de extrapolações',704,315,500,155,39,C.white,true);txt(s,'Falhar na simulação não prova falha inevitável em dados reais.',72,576,1130,72,29,'#C4D6DF');
s=slide('Concluir a tarefa não encerrou a pergunta',90,'A comparação ampla continuou inconclusiva na precisão exigida. O estudo adicional respondeu sob condições fixadas, sem resolver a formulação ampla. O agente escolheu a alternativa simulada autorizada pelo plano porque não tinha um adaptador local validado para as séries reais. Há dados públicos, portanto não dizer que eram inexistentes. Discutir o risco de confundir entrega administrativa e conclusão científica.','Relatório, seção 2 e apêndices B e B.1.');txt(s,'Plano concluído',72,195,1080,80,55,C.teal,true);txt(s,'Comparação ampla\nainda inconclusiva',72,323,1080,160,60,C.navy,true);txt(s,'A resposta mais restrita e o uso de dados simulados\ncontinuaram explícitos no trabalho.',72,535,1090,105,31);
s=slide('Escala e custo do experimento',80,'As linhas incluem comentários e vazios. As análises principais reutilizam dados; não são 45 mil descobertas. A suíte básica soma 217 verificações, com outras auditorias. Não estimar equivalência a anos de trabalho humano sem comparação. O custo de US$ 50 é rateio informado; US$ 1.300 é equivalente em API Standard a preços de 13/09/2026. Fast seria aproximadamente US$ 2.600. A estimativa exclui Gemini, computação local, ferramentas e estudo de caso. Não mede o esforço de compreender e verificar. Detalhes no apoio.','Relatório, apêndices C e E; estimativa_custo_api.json.');txt(s,'26.069',72,190,520,115,79,C.navy,true);txt(s,'linhas em código e testes',76,320,535,65,30);txt(s,'45.528',700,190,505,115,79,C.navy,true);txt(s,'análises principais',704,320,500,65,30);txt(s,'~US$ 50',72,454,500,80,49,C.teal,true);txt(s,'rateio da assinatura informado',76,545,525,73,26);txt(s,'~US$ 1.300',700,454,500,80,49,C.teal,true);txt(s,'equivalente em API Standard',704,545,500,73,26);txt(s,'Volume executado e custo de tokens não medem formação nem qualidade.',72,643,1125,35,22,C.muted);
s=slide('O produto e a pessoa pedem provas distintas',120,'O documento continua permitindo examinar a pesquisa. O caso mostra que sua qualidade aparente não basta para atribuir domínio ao estudante. Identificar uso de IA ou exigir declaração de ferramentas tem papel de transparência, mas não responde se a pessoa entende o que foi feito. Explicar essa distinção sem tratar integridade acadêmica como dispensável.','Relatório, seção 3.');pair(s,'Produto científico','A pergunta é relevante?\nA evidência sustenta a conclusão?','Domínio individual','A pessoa explica as escolhas?\nPrevê o efeito de uma mudança?',215);txt(s,'Detectar o uso de IA não é avaliar aprendizagem.',72,576,1120,70,36,C.orange,true);
s=slide('Mais artigos ou mais conhecimento?',130,'Apresentar como cenário, não previsão comprovada: se agentes aumentarem a produção, atenção de revisores pode limitar o sistema. Contribuições incrementais não perdem valor automaticamente. Uma réplica crítica ou limite bem determinado pode ser mais relevante que alegar uma grande descoberta. No caso, a limitação da aproximação e a inconclusão documentada permitem discutir utilidade. Pedir que a audiência pense no critério que usaria para priorizar um manuscrito.','Relatório, seção 4.',{dark:true});txt(s,'O que a contribuição\npermite saber agora?',72,198,1125,165,62,C.white,true);txt(s,'Uma pequena extensão pode eliminar\numa incerteza importante.',72,433,1125,128,40,'#B8DCE1');txt(s,'O caso abre essa discussão; não demonstra colapso dos periódicos.',72,635,1125,40,22,'#C4D6DF');
s=slide('O que muda entre simular e medir?',110,'O experimento foi computacional. Não comparou produtividade ou qualidade com pesquisa de laboratório. Medir exige vínculo com fenômenos, calibração e desenho de ensaios; dados inéditos podem ampliar a evidência. Isso não garante superioridade do experimental: teoria e computação também contribuem e experimentos também usam automação. A pergunta comum é o que conecta a conclusão à evidência e como a pessoa responde por essa conexão.','Relatório, seção 4.');pair(s,'Simulações','Controles com resposta conhecida\nTeste das hipóteses do modelo','Medições','Confronto com o fenômeno\nControle do instrumento e do ensaio',220);txt(s,'O diferencial é a força da evidência e de sua interpretação.',72,572,1120,80,37,C.teal,true);
s=slide('A orientação pode trabalhar com outra divisão',130,'O agente pode executar implementações e primeiras comparações. A oportunidade é explorar ideias antes inviáveis. O orientador e o estudante precisam construir critérios, escolher problemas e verificar resultados. Isso não retira formulação do estudante; torna importante observá-la. Distinguir atividade para aprender, que pode pedir trabalho individual, da produção científica com delegação ampla. Não reduzir o estudante a operador de agentes.','Relatório, seções 3 e 4.');txt(s,'O agente amplia\na capacidade de executar.',72,188,1125,140,53,C.navy,true);txt(s,'A orientação precisa tornar\no julgamento observável.',72,380,1125,140,53,C.teal,true);txt(s,'Escolher perguntas. Justificar hipóteses. Decidir quando parar.',72,594,1120,70,29);
s=slide('A formação aparece antes da defesa',130,'Propor uma sequência de avaliação concreta. Antes de rodar uma modificação, o estudante registra a previsão e a razão. Depois interpreta o novo gráfico e explica uma divergência. Na defesa reconstrói um argumento central e seus limites, em parte sem assistência quando apropriado. A banca usa registros de acompanhamento para julgar autonomia e profundidade. Para o doutorado e mestrado, discutir níveis esperados sem assumir que número de páginas diferencia os títulos. Estas são propostas pedagógicas, não resultados testados no caso.','Relatório, seções 3 e 5.');rows(s,[['Antes','Prever o efeito de uma alteração.'],['Durante','Explicar o resultado e seus controles.'],['Na defesa','Reconstruir o argumento e seus limites.']],220);txt(s,'Evidências de domínio acumuladas ao longo do curso.',72,596,1120,60,31,C.teal,true);
s=slide('O que passaríamos a exigir?',110,'Encerrar com espaço real para debate. Convidar a audiência a formular um critério para cada questão. O experimento fornece artefatos e decisões verificáveis; a qualidade científica deve ser examinada por especialistas, e aprendizagem requer estudo próprio. Não propor uma única política institucional a partir de um caso. Se houver mais tempo, discutir avaliação independente do manuscrito e comparação entre versões, ainda não realizadas.','Relatório, seção 5.',{dark:true});txt(s,'Da contribuição científica?',72,202,1130,90,52,C.white,true);txt(s,'Do domínio do estudante?',72,346,1130,90,52,'#B8DCE1',true);txt(s,'Do processo de orientação?',72,490,1130,90,52,C.white,true);
s=slide('Apoio: definições das métricas',0,'Números históricos da v1.0.0. O manuscrito de nove páginas é posterior. O total de código arquivado não é deduplicado. O tempo do goal não é CPU. As análises compartilham dados.','Relatório, apêndices C e D.',{backup:true});table(s,[['Medida','Leitura correta'],['26.069 linhas','Módulos, scripts e testes, com comentários e vazios'],['45.528 análises','Quatro campanhas, com dados compartilhados'],['54 h 56 min','Calendário da criação ao encerramento do goal'],['30 h 51 min','Contador do goal; não mede tempo de formação']],[310,826],185,400,25);
s=slide('Apoio: hipóteses da estimativa de custo',0,'Aplicação dos preços oficiais Astra Standard de 13/09/2026 aos registros únicos por resposta. Até o goal são 6.510 respostas, com agente principal e três subagentes, totalizando US$ 1.289,34. Os complementos científicos acrescentam US$ 14,29. 97,56% da entrada veio de cache. Gravações de cache zero no registro; cobrar toda entrada nova como gravação acrescentaria cerca de US$ 53, mantida a reutilização. Fast dobra o preço. Não incluir o contador do goal nem somar raciocínio duas vezes. Exclui Gemini, computação local, ferramentas adicionais e estudo de caso. US$ 50 é estimativa do usuário sobre rateio, não tarifa de API.','Relatório, apêndice E; estimativa_custo_api.json; developers.openai.com/api/docs/models/gpt-6-astra.',{backup:true});table(s,[['Categoria até o goal','Milhões de tokens','US$'],['Entrada nova','20,58','205,84'],['Entrada em cache','822,05','822,05'],['Saída, com raciocínio','5,23','261,46']],[590,326,220],185,315,25);txt(s,'~US$ 1.300 Standard / ~US$ 2.600 Fast',72,539,1120,60,36,C.teal,true);txt(s,'Com complementos científicos. Estimativas, não faturas.',72,611,1120,45,26,C.muted);
s=slide('Apoio: documentos para examinar o caso',0,'O repositório reúne PDFs e fontes, evidências e notas de revisão. O corpo do relatório discute decisões e formação; os apêndices guardam interações, métricas e método. Conversas privadas não foram transcritas.','https://github.com/flavioluiz/TGdoWayne',{backup:true});txt(s,'github.com/flavioluiz/TGdoWayne',72,220,1130,85,43,C.teal,true);txt(s,'Relatório com evidências e apêndices\nDissertação e manuscrito revisado\nCódigo, resultados e registros de revisão',72,380,1130,205,34);
await fs.mkdir(TMP,{recursive:true});
await fs.writeFile(path.join(TMP,'notes.json'),JSON.stringify(notes,null,2));
const candidate=path.join(TMP,'candidate.pptx');await (await PresentationFile.exportPptx(p)).save(candidate);
for(let i=0;i<p.slides.items.length;i++){const slide=p.slides.items[i];const b=await p.export({slide,format:'png',scale:1});await fs.writeFile(path.join(TMP,`slide-${String(i+1).padStart(2,'0')}.png`),new Uint8Array(await b.arrayBuffer()));}
await fs.mkdir(path.join(TMP,'exported'),{recursive:true});
const final=path.join(TMP,'exported',`final-${Date.now()}.pptx`);
await finalizePresentation({workspaceDir:ROOT,candidatePath:candidate,finalPath:final,pythonExecutable:PY,integrityValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit',...tableOwners.flatMap(n=>['--require-native-table-slide',String(n)])],requiredNativeChartOwnerSlides:chartOwners,requiredNativeTableOwnerSlides:tableOwners,materializeLiteralChartWorkbooks:true,fontPolicy:{basis:'design',families:[FONT]},verifyArtifactToolImport:true,receiptPath:path.join(TMP,`validation-${path.basename(final,'.pptx')}.json`)});
await fs.writeFile(path.join(TMP,'final-path.txt'),final);
console.log(JSON.stringify({slides:p.slides.items.length,main_seconds:notes.reduce((a,b)=>a+b.seconds,0),final}));
