import fs from 'node:fs/promises';
import path from 'node:path';
import { Presentation, PresentationFile } from '@oai/artifact-tool';
const SKILL=process.env.PRESENTATIONS_SKILL;
if(!SKILL)throw new Error('Set PRESENTATIONS_SKILL');
const {resolvePresentationFont,applyPresentationChartFont,finalizePresentation}=await import(path.join(SKILL,'container_tools/artifact_tool_utils.mjs'));
const ROOT=process.env.PROJECT_ROOT;
if(!ROOT)throw new Error('Set PROJECT_ROOT to the repository root');
const TMP=path.join(ROOT,'tmp/presentations/experimento');
const PY=process.env.PYTHON_EXECUTABLE || 'python3';
const FONT=resolvePresentationFont({fontFamily:'Arial'});
const C={navy:'#17324D',teal:'#087F8C',ink:'#253643',muted:'#586B79',ivory:'#F7F5F0',orange:'#B35B32',white:'#FFFFFF'};
const p=Presentation.create({slideSize:{width:1280,height:720}});
const notes=[]; const chartOwners=[]; const tableOwners=[];
function txt(s,str,x,y,w,h,size=30,color=C.ink,bold=false){const t=s.shapes.add({geometry:'textbox',name:str.slice(0,55),position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});t.text=str;t.text.style={typeface:FONT,fontSize:size,color,bold,autoFit:'none',verticalAlignment:'top',insets:{top:0,left:0,right:0,bottom:0}};return t;}
function slide(title,seconds,note,source,{dark=false,backup=false}={}){const s=p.slides.add();s.background.fill=dark?C.navy:C.ivory;const n=p.slides.items.length;txt(s,title,72,48,1136,110,44,dark?C.white:C.navy,true);txt(s,backup?'Apoio':`${n} / 21`,1110,677,98,24,17,dark?'#B6CCD8':C.muted);s.speakerNotes.textFrame.setText(`${backup?'Apoio opcional':`Tempo sugerido: ${seconds} s`}\n\n${note}\n\nFontes: ${source}`);notes.push({slide:n,title,seconds,backup,note,source});return s;}
function lead(s,str,y=175,dark=false){txt(s,str,72,y,1130,150,40,dark?C.white:C.navy,true);}
function pair(s,leftTitle,left,rightTitle,right,y=230){txt(s,leftTitle,72,y,520,54,30,C.teal,true);txt(s,left,72,y+74,520,275,29);txt(s,rightTitle,690,y,520,54,30,C.teal,true);txt(s,right,690,y+74,520,275,29);}
function rows(s,arr,y=200){arr.forEach((r,i)=>{txt(s,r[0],72,y+i*115,265,80,30,C.teal,true);txt(s,r[1],380,y+i*115,800,90,29);});}
async function img(s,file,x,y,w,h){s.images.add({blob:new Uint8Array(await fs.readFile(path.join(ROOT,'presentations/experimento/assets',file))),contentType:'image/png',alt:`Página do documento ${file}`,fit:'contain',position:{left:x,top:y,width:w,height:h}});}
function table(s,values,widths,y=190,h=360,size=27){const tb=s.tables.add({rows:values.length,columns:values[0].length,left:72,top:y,width:1136,height:h,columnWidths:widths,values});tb.borders.assign({fill:'#D7DFE2',width:.5,style:'solid'});for(let r=0;r<values.length;r++){tb.rows[r].height=h/values.length;for(let c=0;c<values[0].length;c++){const cell=tb.getCell(r,c);cell.fill=r===0?C.navy:C.ivory;cell.text.style={typeface:FONT,fontSize:size,color:r===0?C.white:C.ink,bold:r===0,insets:{top:12,bottom:8,left:14,right:14}};}}tableOwners.push(p.slides.items.length);return tb;}
let s=slide('Pesquisa acadêmica com agentes de IA',35,'Apresentar o experimento como estudo de caso. O tema de ondas gravitacionais forneceu a tarefa científica, mas a pergunta desta apresentação é sobre automação, formação e avaliação. Não pressupor conhecimento de física.','Relatório do estudo de caso, introdução.',{dark:true});txt(s,'Um experimento de criação\nde dissertação e artigo',72,230,1050,185,60,C.white,true);txt(s,'Codex na execução\nGemini em dois ciclos de revisão',75,483,970,100,30,'#C5DDE3');
s=slide('A pergunta do experimento',65,'Distinguir qualidade do produto, aprendizagem e responsabilidade. A proposta era observar até onde o agente iria com orientação científica inicial mínima. O objetivo não é detectar uso de IA em textos.','Relatório, seções 8 a 10.');lead(s,'O que esperamos de um pesquisador quando parte da pesquisa pode ser delegada a agentes?');pair(s,'Produto científico','A pergunta importa?\nOs resultados se sustentam?','Formação da pessoa','Ela compreende o trabalho?\nConsegue decidir o próximo passo?',360);
s=slide('O ponto de partida',80,'O proponente forneceu um trabalho de graduação e pediu extensões implementáveis com potencial de artigo. Declarou não dominar a área. O agente precisou procurar antecedentes e formular o recorte. A imagem é a página real do TG e não uma representação gerada.','TG_Wayne.pdf, página 1. Relatório, seções 1 e 3.');txt(s,'Um trabalho de graduação\nUma intenção ampla\nNenhuma hipótese nova fornecida no início',72,220,690,210,36,C.navy,true);txt(s,'Pedido: propor uma continuação de mestrado, implementar e validar.',72,495,680,105,29);await img(s,'tg-01.png',865,160,320,450);
s=slide('Quem tomou quais decisões',70,'A participação humana foi de direção, recursos, formato e mediação dos pareceres. O Codex coordenou três subagentes e executou o trabalho científico. O Gemini elaborou dois pareceres, conforme esclarecido pelo usuário. Não se conhece sua versão.','Conversa de execução. Relatório, seções 2, 2.1 e 4.');rows(s,[['Usuário','Definiu a intenção, acompanhou recursos e encaminhou feedback.'],['Codex (Astra)','Formulou o recorte, implementou, testou e redigiu.'],['Gemini','Revisou a dissertação e, depois, o manuscrito.']]);
s=slide('Cronologia do experimento',85,'Todos os horários são de Brasília. A primeira fase incluiu pausas e mudanças de estado. A revisão do artigo ocorreu depois do goal original e não está incluída em seu contador.','Relatório, seções 1, 2, 2.1 e 7.');table(s,[['Quando','Marco'],['10 set.','TG, proposta e início do goal'],['11 set.','Simulações, resultados parciais e pausa'],['12 set.','Retomada e parecer sobre a dissertação'],['13 set., 01:04','Goal concluído e dissertação consolidada'],['13 set., 11:14','Manuscrito revisado após novo parecer']],[310,826],178,405,26);
s=slide('Como o agente procurou novidade',85,'Os resultados centrais do TG já tinham publicação derivada. O agente considerou caminhos alternativos e encontrou antecedentes próximos. A decisão foi reduzir a reivindicação de novidade a uma comparação controlada, e não inventar as técnicas empregadas. Não houve revisão sistemática exaustiva.','output/pesquisa/proposta_mestrado.md e docs/literatura/decisao_recorte.md.');rows(s,[['Antecedentes','Reconheceu resultados já publicados.'],['Alternativas','Comparou possíveis extensões teóricas e numéricas.'],['Recorte','Escolheu testar quando simplificações mudam uma análise.']]);txt(s,'Originalidade candidata, ainda sujeita a avaliação especializada.',72,602,1100,40,24,C.orange);
s=slide('Execução orientada por etapas',70,'O plano tinha 13 marcos. Não se esperou o cronograma convencional de 24 meses. Cada marco previa entregas verificáveis e PDF. Houve versões intermediárias, dificuldades de recursos e mudanças de método. A etapa concluída não garante que sua pergunta tenha resposta definitiva.','implementation_plan/roadmap.json. Relatório, seção 4.');lead(s,'13 marcos concluídos');rows(s,[['Construção','Revisão, base teórica, modelo e simulador.'],['Experimentos','Calibração, comparações e robustez.'],['Consolidação','Reprodução, dissertação e manuscrito.']],285);
s=slide('Os produtos do estudo',70,'As imagens mostram páginas reais dos documentos. A dissertação final tem 167 páginas. O manuscrito tinha sete na v1.0.0 e passou a nove. Também existem duas apresentações científicas. O produto atual continua sem defesa institucional ou submissão editorial.','output/pdf/v1.0.0/dissertacao.pdf, página 1. article/manuscript.pdf, página 1.');await img(s,'dissertacao-001.png',130,175,300,380);await img(s,'artigo-1.png',690,175,300,380);txt(s,'Dissertação: 167 páginas',90,583,505,45,30,C.navy,true);txt(s,'Artigo: 9 páginas',720,583,460,45,30,C.navy,true);
s=slide('Escala do trabalho executado',75,'O gráfico mede linhas físicas na tag v1.0.0, incluindo comentários e linhas vazias. As 45.528 análises somam C07, C09, C10 e C11 e compartilham dados, portanto não são observações independentes. Não somar reproduções como novos experimentos.','evidencias.json, code_groups. Relatório, seção 6.');const ch=s.charts.add('bar',{position:{left:70,top:185,width:710,height:360},categories:['Módulos','Scripts','Testes'],series:[{name:'Linhas físicas',values:[7138,15320,3611],fill:C.teal}],barOptions:{direction:'bar',grouping:'clustered',gapWidth:70},hasLegend:false,titlePlacement:'none',dataLabels:{showValue:true,position:'outEnd',textStyle:{fontSize:24,typeface:FONT}},xAxis:{numberFormatCode:'#,##0',textStyle:{fontSize:22,typeface:FONT}},yAxis:{textStyle:{fontSize:24,typeface:FONT}},chartFill:C.ivory,plotAreaFill:C.ivory});applyPresentationChartFont(ch,{fontFamily:FONT});chartOwners.push(9);txt(s,'26.069',860,205,320,85,64,C.navy,true);txt(s,'linhas em módulos,\nscripts e testes',860,303,320,90,28);txt(s,'45.528',860,425,320,80,56,C.navy,true);txt(s,'análises principais',860,517,320,55,27);txt(s,'Base histórica v1.0.0. Quantidade mede execução, não qualidade científica.',72,602,1110,45,23,C.muted);
s=slide('Tempo de execução e tempo de formação',75,'O goal retornou 111086 segundos. O calendário entre criação e encerramento foi 197802 segundos, com pausas. A revisão adicional do artigo levou cerca de 6min37s no Codex, sem incluir o Gemini. Não é uma comparação de produtividade com um estudante.','Eventos do goal e complementos_pos_goal.json. Relatório, seção 7.');txt(s,'30 h 51 min',72,205,670,100,76,C.navy,true);txt(s,'contador do goal original',76,323,750,55,32);txt(s,'54 h 56 min',72,433,670,95,65,C.teal,true);txt(s,'intervalo no calendário, com pausas',76,541,780,50,29);txt(s,'Compreender e\nvalidar exigem\ntempo próprio.',890,235,320,235,35,C.orange,true);
s=slide('Custos: uma ordem de grandeza',75,'O usuário estima ter gasto uma semana de sua cota, à qual atribui cerca de US$ 50. É um rateio da assinatura, sem equivalência contratual com créditos. A conta da API Standard aplica preços de 13/09/2026 aos registros individuais do agente principal e três subagentes: US$ 1.289,34 até o goal e US$ 14,29 de complementos científicos, total de US$ 1.303,63. Entrada sem cache: 20.583.691 tokens; em cache: 822.046.336; saída: 5.229.122. 97,56% da entrada foi cache. Não somar o contador do goal. Fast dobra o preço. Gravações de cache não aparecem nos registros; considerar toda entrada nova como gravação acrescentaria cerca de US$ 53, mantida a reutilização. Exclui Gemini, ferramentas, computação local e elaboração do estudo de caso. Uma nova execução pode custar diferente.','Relatório, seção 7.1; estimativa_custo_api.json. Preços em developers.openai.com/api/docs/models/gpt-6-astra, consultados em 13/09/2026.');txt(s,'US$ 50',72,205,520,90,66,C.teal,true);txt(s,'Rateio da assinatura\nEstimativa do usuário',72,320,520,105,30);txt(s,'US$ 1.300',690,205,520,90,66,C.navy,true);txt(s,'Equivalente em API Standard\nConsumo registrado × preços',690,320,520,105,30);txt(s,'API Fast: cerca de US$ 2.600 para os mesmos tokens.',72,492,1136,65,31,C.orange,true);txt(s,'Estimativas, não faturas. Excluem Gemini, computação local, tarifas\nadicionais de ferramentas e elaboração do estudo de caso.',72,588,1136,72,24,C.muted);
s=slide('Um controle expôs confiança excessiva',85,'Explicar cobertura como a frequência com que uma faixa estimada contém o valor usado para gerar os dados. Em um parâmetro de ruído, uma análise nominal de 90% atingiu 313 de 500 casos, 62,6%. Não generalizar esse número para todos os parâmetros ou todos os métodos. A incerteza numérica levava a contagens de 299 a 325, ainda longe de 450.','docs/revisao_cientifica_1.md e results/C13/review_efac_coverage.json.');txt(s,'90%',72,200,520,100,76,C.teal,true);txt(s,'Cobertura nominal\nesperada',72,328,520,110,32);txt(s,'62,6%',690,200,520,100,76,C.orange,true);txt(s,'Cobertura observada\nem um parâmetro',690,328,520,110,32);txt(s,'313 de 500 casos continham a verdade simulada.',72,508,1110,55,35,C.navy,true);txt(s,'As simulações permitiram detectar uma limitação da aproximação.',72,586,1110,45,27,C.muted);
s=slide('Correções e perguntas ainda abertas',80,'Separar erro editorial, problema de execução e limitação científica. A descrição das aproximações em uma versão estava incorreta, mas o cálculo usava a semântica correta. A comparação ampla continuou inconclusiva. Um estudo com 50 casos e parâmetros fixados respondeu a uma pergunta menor com precisão.','docs/c12_errata_v0110.md, docs/revisao_cientifica_1.md.');rows(s,[['Texto','Corrigiu uma descrição incompatível com o código.'],['Execução','Recuperou cálculos e insumos após falhas operacionais.'],['Escopo','Resolveu um estudo mais restrito, preservando a inconclusão ampla.']]);
s=slide('Dois ciclos de revisão com Gemini',75,'O primeiro parecer motivou novos estudos, como as 300 análises condicionais e o teste de ajuste temporal. O segundo foi uma revisão do manuscrito e não iniciou novas simulações. Não se dispõe da conversa original do Gemini ou de sua versão.','Relatório, seções 2 e 2.1. article/REVISION_NOTES.md.');pair(s,'Dissertação','Críticas científicas\nNovos estudos pontuais\nRevisão do texto e figuras','Manuscrito','Estrutura e interpretação\nFluxograma e referências\nResultados existentes',208);txt(s,'O usuário mediou a revisão e o Codex conferiu as recomendações.',72,585,1100,50,28,C.navy,true);
s=slide('O Codex filtrou o segundo parecer',80,'Mostrar o valor e o risco do feedback automatizado. O agente aceitou melhorias de exposição, mas as notas de revisão recusam novidade absoluta, certeza de falha em dados reais e amplificações extremas não demonstradas. O ponto é o contraste entre persuasão retórica e suporte científico.','article/REVISION_NOTES.md, commit 26ae3ac.');pair(s,'Melhorias incorporadas','Contribuição mais clara\nResultados reorganizados\nDiagrama explicativo','Generalizações limitadas','Ineditismo absoluto\nFalha inevitável em dados reais\nCausas não demonstradas',205);txt(s,'A revisão ampliou o artigo de 7 para 9 páginas, sem novas simulações.',72,585,1120,50,27,C.navy,true);
s=slide('O que o caso demonstra',80,'Evitar extrapolar o estudo de caso. Os produtos existem e há rastros de execução. Não houve avaliação científica independente completa, teste de aprendizagem ou aceitação editorial. Uma revisão entre modelos é observável, mas seu ganho de qualidade não foi medido por avaliadores externos.','Relatório, seções 8 a 10.');pair(s,'Evidência disponível','Formulação e execução extensas\nControles e correções\nProdutos reproduzíveis no escopo','Questões abertas','Originalidade definitiva\nQualidade julgada por especialistas\nAprendizagem e ganho de produtividade',190);
s=slide('A divisão do trabalho pode mudar',80,'Oportunidades: explorar ideias que não chegariam à implementação e testar mais alternativas. Dificuldade: produzir pode se tornar mais rápido que compreender e validar. Não apresentar esse deslocamento como medição de todo o campo, mas como hipótese sustentada pela experiência do caso.','Relatório, seções 8 e 9.');lead(s,'Mais capacidade de explorar ideias');pair(s,'Trabalho delegável','Primeiras formulações\nCódigo e controles\nOrganização dos resultados','Trabalho a avaliar','Escolha da pergunta\nJulgamento das evidências\nDecisão de continuar ou parar',340);
s=slide('Formação precisa aparecer no processo',75,'Destacar responsabilidades compartilhadas pelo programa, orientador e estudante. Propor avaliações distribuídas e distinguir exercício para aprender de tarefa de produção. A defesa deve complementar esse percurso. O caso não testa a eficácia destas propostas.','Relatório, seção 8.');rows(s,[['Antes de executar','Explicar a hipótese e prever o efeito de uma mudança.'],['Durante o trabalho','Interpretar controles e justificar escolhas.'],['Ao concluir','Reconstruir o argumento e responder por seus limites.']]);
s=slide('Relevância e capacidade de revisão',70,'Discutir possíveis consequências de aumento da produção sem afirmar colapso observado de periódicos. Origem humana ou de IA não decide relevância. Contribuições incrementais podem ser valiosas se resolvem incerteza importante. Oportunidade de usar a capacidade extra para profundidade, controle e síntese.','Relatório, seção 9.');lead(s,'Mais resultados exigem mais capacidade de julgar o que importa');txt(s,'Uma contribuição pode valer pela pergunta que resolve, pela incerteza que elimina ou pelo limite que estabelece.',72,370,1080,140,36);txt(s,'Contagem de artigos e volume de código não substituem essa avaliação.',72,580,1110,50,27,C.orange);
s=slide('Próximas avaliações do experimento',75,'Estas são propostas ainda não executadas. Especialistas poderiam comparar artigo antes e depois do Gemini, checar argumentos e reproduzir resultados centrais. Para aprendizagem seria necessário outro desenho com estudantes e medidas antes e depois.','Relatório, seção 10.');rows(s,[['Qualidade científica','Especialistas examinam as conclusões centrais.'],['Efeito da revisão','Comparação cega entre versões do manuscrito.'],['Formação e custo','Medidas de compreensão e esforço total de verificação.']]);
s=slide('Questões para discussão',110,'Reservar cerca de dois minutos para encerrar ou abrir uma conversa. Na versão de 20 minutos, selecionar apenas uma questão. Na de 30 minutos, usar o tempo restante para ouvir respostas. Não tratar os produtos como títulos acadêmicos aprovados.','Relatório do estudo de caso, discussão.',{dark:true});txt(s,'Que competências precisam\nser demonstradas pessoalmente?',72,195,1130,125,44,C.white,true);txt(s,'Que perguntas passam a valer a pena\nquando executar custa menos?',72,355,1130,120,40,C.white);txt(s,'Como repartir o esforço de verificar?',72,525,1130,90,40,'#B8DCE1');
s=slide('Apoio: leitura correta das métricas',0,'Abrir apenas se perguntarem pelas contagens. Todas são do fechamento v1.0.0, exceto o manuscrito revisado. Os arquivos de evidências documentam regras e exclusões.','evidencias.json, complementos_pos_goal.json.',{backup:true});table(s,[['Medida','Definição'],['26.069 linhas','Módulos, scripts e testes, com linhas vazias'],['91.347 linhas','Inclui código arquivado e cópias, sem deduplicação'],['45.528 análises','Quatro campanhas, com dados compartilhados'],['25.719.766 tokens','Contador do goal; custo calculado por outra fonte']],[330,806],183,365,25);
s=slide('Apoio: documentos e fontes',0,'Links completos também estão nas notas e no README. A apresentação usa a conversa de execução e artefatos do próprio projeto. Discussões privadas não foram transcritas.','https://github.com/flavioluiz/TGdoWayne',{backup:true});txt(s,'Repositório TGdoWayne',72,185,1100,65,38,C.navy,true);txt(s,'github.com/flavioluiz/TGdoWayne',72,270,1100,60,32,C.teal);txt(s,'Relatório do estudo de caso e evidências\nNotas da revisão do manuscrito\nDissertação v1.0.0 e arquivos de reprodução\nRoteiro desta apresentação com fontes por slide',72,395,1120,215,30);
await fs.mkdir(TMP,{recursive:true});
await fs.writeFile(path.join(TMP,'notes.json'),JSON.stringify(notes,null,2));
const candidate=path.join(TMP,'candidate.pptx');await (await PresentationFile.exportPptx(p)).save(candidate);
for(let i=0;i<p.slides.items.length;i++){const slide=p.slides.items[i];const b=await p.export({slide,format:'png',scale:1});await fs.writeFile(path.join(TMP,`slide-${String(i+1).padStart(2,'0')}.png`),new Uint8Array(await b.arrayBuffer()));}
await fs.mkdir(path.join(TMP,'exported'),{recursive:true});
const final=path.join(TMP,'exported',`final-${Date.now()}.pptx`);
await finalizePresentation({workspaceDir:ROOT,candidatePath:candidate,finalPath:final,pythonExecutable:PY,integrityValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit',...tableOwners.flatMap(n=>['--require-native-table-slide',String(n)])],requiredNativeChartOwnerSlides:chartOwners,requiredNativeTableOwnerSlides:tableOwners,materializeLiteralChartWorkbooks:true,fontPolicy:{basis:'design',families:[FONT]},verifyArtifactToolImport:true,receiptPath:path.join(TMP,`validation-${path.basename(final,'.pptx')}.json`)});
await fs.writeFile(path.join(TMP,'final-path.txt'),final);
console.log(JSON.stringify({slides:p.slides.items.length,main_seconds:notes.reduce((a,b)=>a+b.seconds,0),final}));
